# Generated by Django 2.2.2 on 2019-06-17 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190617_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='The Tavern Game', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 17, 16, 20, 48, 496219), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 17, 16, 20, 48, 497011), verbose_name='Date'),
        ),
    ]
