# Generated by Django 2.2.2 on 2019-06-17 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20190617_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='Left blank', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 17, 16, 39, 10, 280132), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 17, 16, 39, 10, 280917), verbose_name='Date'),
        ),
    ]
