# Generated by Django 2.2.2 on 2019-06-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190617_1639'),
        ('main_app', '0008_auto_20190617_1656'),
        ('main_app', '0009_auto_20190617_1650'),
    ]

    operations = [
    ]
