# Generated by Django 2.2.2 on 2019-06-19 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20190617_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 19, 4, 5, 24, 486187), verbose_name='Date'),
        ),
    ]
