# Generated by Django 2.2 on 2019-06-19 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20190619_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 19, 19, 19, 12, 556969), verbose_name='Date'),
        ),
    ]
