# Generated by Django 2.2.2 on 2019-06-19 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20190619_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 19, 19, 43, 23, 140859), verbose_name='Date'),
        ),
    ]
