# Generated by Django 2.2.2 on 2019-06-19 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20190619_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='character',
        ),
        migrations.AlterField(
            model_name='character',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 19, 20, 3, 48, 273827), verbose_name='Date'),
        ),
    ]
