# Generated by Django 2.2.2 on 2019-08-01 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20190801_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 1, 23, 45, 25, 196832), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 1, 23, 45, 25, 197727), verbose_name='Date'),
        ),
    ]
